### ISSUE TITLE
Support for "ra" ("react-admin" version 2, aka "admin-on-rest version 2)

### ISSUE THREAD

**Issue by afilp** [kimkha/aor-loopback#13]
Hi,

I will upgrade to AOR version 2 today (now known as "react-admin" version 2).

Because of the rename of "admin-on-rest" to "react-admin", I believe that there is a need to have a different npm package, like they already did with aor-dependent-input: they created another one for ra: https://www.npmjs.com/package/ra-dependent-input

Can this be done please?

Thanks!

**Comment by kimkha** [comment]
Please use [loopback-component-react-admin](https://github.com/kimkha/loopback-component-react-admin) instead.
