### ISSUE TITLE
Support for DELETE_MANY and UPDATE_MANY, for 'next' branch

### ISSUE THREAD

**Issue by afilp** [kimkha/aor-loopback#16]
Could you please add support for these?
https://github.com/marmelab/admin-on-rest/blob/next/UPGRADE.md#data-providers-should-support-two-more-types-for-bulk-actions

I am using the 'next' branch and this would be great, if possible!

Thanks!

**Comment by afilp** [comment]
@kimkha These 2 are actually required, otherwise the bulk solution does not work. Is this possible? Thanks a lot!

**Comment by kimkha** [comment]
I will take a look... I didn't have much time to work on it... Thanks

**Comment by kimkha** [comment]
Ah, do you have time to work on this? If yes, I'm happy to assign you as a maintainer

**Comment by afilp** [comment]
I am afraid not at the moment...! I am in a pressing situation to deliver a project. Thank you for your offer though.

P.S. If you do so, I would recommend that you also create a new repository (and npm package) so that the `name` is changed. See here why:

https://github.com/kimkha/aor-loopback/issues/13

**Comment by kimkha** [comment]
Please use [loopback-component-react-admin](https://github.com/kimkha/loopback-component-react-admin) instead.
