### ISSUE TITLE
The X-Total-Count header is missing in the HTTP Response.

### ISSUE THREAD

**Issue by cyclops24** [kimkha/aor-loopback#2]
Hi @kimkha I try using your RestClient but it's return below error:
```
The X-Total-Count header is missing in the HTTP Response. The jsonServer REST client expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?
```

Do you have any idea?

**Comment by kimkha** [comment]
Because the Loopback server didn't support that header. But you can add it by using my another component: https://github.com/kimkha/loopback3-xTotalCount

**Comment by kimkha** [comment]
Because the Loopback server didn't support that header. But you can add it by using my another component: https://github.com/kimkha/loopback3-xTotalCount

**Comment by cyclops24** [comment]
@kimkha Thanks for your quick response. 😉 
I add [this](https://github.com/kimkha/loopback3-xTotalCount) package and add related line to `server/server.js` file but my admin ui still return previous error:
```
'use strict';

var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback();
require('loopback3-xtotalcount')(app);
...
```

**Comment by kimkha** [comment]
How about add this to your `component-config.json`?

```
"loopback3-xtotalcount": {
    "pattern": [
      "*.find"
    ]
  }
```

**Comment by cyclops24** [comment]
No it's still show above error message.

**Comment by kimkha** [comment]
Did you remove `require('loopback3-xtotalcount')(app);` on your `server.js`?

**Comment by kimkha** [comment]
Sounds strange....

**Comment by cyclops24** [comment]
NO `require('loopback3-xtotalcount')(app);` still there.

**Comment by kimkha** [comment]
Try to remove it please, just use component setting.

**Comment by cyclops24** [comment]
After remove that [this warning message](https://github.com/kimkha/loopback3-xTotalCount/issues/1) gone but it's still show bellow error message on admin ui client:
```
The X-Total-Count header is missing in the HTTP Response. The jsonServer REST client expects responses for lists of resources to contain this header with the total number of results to build the pagination. If you are using CORS, did you declare X-Total-Count in the Access-Control-Expose-Headers header?
```

**Comment by kimkha** [comment]
Can you use API Explorer and call `find` API, then check the response header?

Or can you post your code on here?

**Comment by cyclops24** [comment]
My project is a little big and I can't post all of code. Which part of code needs now?
I call a GET to `http://0.0.0.0:3001/api/Projects` and it's response header:
```
{
  "content-type": "application/json; charset=utf-8",
  "content-length": "164",
  "etag": "W/\"a4-zZqbHh2TejGRI9xacJgwQvt2KYM\"",
  "vary": "Origin",
  "access-control-allow-credentials": "true",
  "x-xss-protection": "1; mode=block",
  "x-frame-options": "DENY",
  "x-download-options": "noopen",
  "x-content-type-options": "nosniff",
  "x-total-count": "1",
  "date": "Wed, 10 May 2017 16:12:37 GMT"
}
```

**Comment by kimkha** [comment]
Already had `"x-total-count": "1"` in response... but somehow...

Could you please show me your `App.js` file?

**Comment by cyclops24** [comment]
Is it need `Access-Control-Expose-Headers` too in header?

**Comment by cyclops24** [comment]
it's my `App.js`:
```
import React from 'react';
import { Admin, Resource } from 'admin-on-rest';
import loopbackRestClient from 'aor-loopback';

import { ProjectList } from './projects';

const App = () => (
    <Admin restClient={loopbackRestClient('http://0.0.0.0:3001/api')}>
        <Resource name="projects" list={ProjectList} />
    </Admin>
);

export default App;
```

**Comment by kimkha** [comment]
Maybe, if your react apps and your loopback use different domain.

**Comment by cyclops24** [comment]
My react admin-on-rest URL is: `http://0.0.0.0:3000` and my loopback URL is: `http://0.0.0.0:3001`

**Comment by kimkha** [comment]
Please try to use `Access-Control-Expose-Headers` on Loopback. And let me know the result, please... :)

**Comment by cyclops24** [comment]
Can you guide me how we can add `Access-Control-Expose-Headers` to LoopBack?

**Comment by cyclops24** [comment]
I have to go home now. I continue this project and check this issue after this. 😉

**Comment by kimkha** [comment]
Actually, I don't know how to add that header.

Ah, did you open developer console and see Network tab?

**Comment by cyclops24** [comment]
Hi @kimkha ,
It's my network tab image:
![aor_issue1](https://cloud.githubusercontent.com/assets/8266479/25946973/9a58ba44-3662-11e7-81e9-6264f91039de.png)

**Comment by kimkha** [comment]
I found it. To allow other headers over cross domain, we must expose in the setting of cors.

So, open `middleware.json`, add `"exposedHeaders": "X-Total-Count"` under `initial.cors.params`

**Comment by cyclops24** [comment]
Hi @kimkha ,
It's fixed after add `"exposedHeaders": "X-Total-Count"` to `middleware.json`.
Thanks for your attention.
I think https://github.com/kimkha/loopback3-xTotalCount need some documentation about it.
