### ISSUE TITLE
So this doesn't work with react-admin?

### ISSUE THREAD

**Issue by benwinding** [kimkha/aor-loopback#20]
I understand it says the plugin will only work with older versions of Admin on Rest.

Is there any chance this can be updated to work with the new react-admin?

**Comment by kimkha** [comment]
I will try to do it soon... Thanks

**Comment by Kmaschta** [comment]
In the meantime, I will remove this library from the React Admin documentation https://github.com/marmelab/react-admin/pull/2300/files
It will still be available on the Admin on Rest documentation.

Feel free to open a PR again when your lib will be ready for RA 2.3.x !

**Comment by kimkha** [comment]
Please use [loopback-component-react-admin](https://github.com/kimkha/loopback-component-react-admin) instead.

**Comment by benwinding** [comment]
So I ended up implementing a provider also, with realtime updates and other features too.

 [react-admin-firebase](https://github.com/benwinding/react-admin-firebase)

**Comment by kimkha** [comment]
Oh, that's really cool!
