### ISSUE TITLE
Use PATCH instead of PUT for update

### ISSUE THREAD

**Issue by johannesfritsch** [kimkha/aor-loopback#7]
E.g. if I want to update the default loopback user model I have to specify all the attributes when using PUT, which is not even possible as I can not have my user re-enter the password every time.

I created a fork under Zoom7/aor-loopback for the time being that does simply replace PUT with PATCH, so I can proceed. Maybe this is also an option for aor-loopback.

**Comment by johannesfritsch** [comment]
Just saw that there is a pending PR for this. Please consider accepting it. It seems reasonable to me :-)

**Comment by kimkha** [comment]
I'm still thinking about that PR. Is it better? I'm not sure if we change to PATCH it will work for other cases?

**Comment by kimkha** [comment]
I also merge that PR... :)

**Comment by kodepareek** [comment]
Guys this is a pretty big  change. I will have to go through my entire API and make appropriate changes now. Did we follow Semver for this?

While I agree that Patch is a better option that put any day. This kind of change should have been more carefully done.

**Comment by kimkha** [comment]
I really think 'PATCH' is better than 'PUT'. That's why I accept this PR.

The difference between them is: 'PUT' can "delete" some fields. But with 'admin-on-rest', it's useless, because 'admin-on-rest' don't support "deleting field", only set to `null` (or empty `''`).

Thank you anyway.
