### ISSUE TITLE
ReferenceArrayInput doesn't seem to work

### ISSUE THREAD

**Issue by marcquark** [kimkha/aor-loopback#8]
Hi kimkha,

first of all thanks a lot for writing this client. This is really helpful and speeds up the development process.

I'm having trouble getting the ReferenceArrayInput to work. I implemented it as described [here](https://marmelab.com/admin-on-rest//Inputs.html#referencearrayinput)

Displaying the same property in a ReferenceArrayField works as expected. Also, the ReferenceArrayInput correctly displays the possible Choices (Tags, in my case). However when i click on one of them, nothing happens (they don't get added to the list of Tags). When i add them manually through the Loopback Explorer, they get displayed correctly and i can also remove them.

I don't see any console output or network traffic. One thing that is different from the examples is that my IDs are not numbers but strings. Could that be the issue? Let me know if there's anything i can do to help debug/fix the problem.

Regards

**Comment by marcquark** [comment]
Hi again,

i just found this issue: [https://github.com/marmelab/admin-on-rest/issues/1117](https://github.com/marmelab/admin-on-rest/issues/1117)

Changing the following dependencies did the trick for me. No issues with your code, sorry for posting in the wrong place.

`"dependencies": {
    "react": "^15",
    "react-dom": "^15.3.2",
  },`

I left everything else as it was (aor 1.3.2)

**Comment by kimkha** [comment]
Thank you! :)
